apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-jellyseerr-python-scripts
data:
{{ ( tpl (.Files.Glob "config/jellyseerr/init-jellyseerr.py" ).AsConfig . ) | indent 2 }}

---

apiVersion: v1
kind: ConfigMap 
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-failed, before-hook-creation
  name: init-qbittorrent-python-script
data:
{{ ( tpl (.Files.Glob "config/qbittorrent/init-qBitTorrent.py" ).AsConfig . ) | indent 2 }}