apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-jellyseerr-python-scripts
data:
{{ ( tpl (.Files.Glob "config/scripts/init-jellyseerr.py" ).AsConfig . ) | indent 2 }}
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-radarr-script
data:
{{ ( tpl (.Files.Glob "config/scripts/init-radarr.py" ).AsConfig . ) | indent 2 }}
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-sonarr-script
data:
{{ ( tpl (.Files.Glob "config/scripts/init-sonarr.py" ).AsConfig . ) | indent 2 }}
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-prowlarr-script
data:
{{ ( tpl (.Files.Glob "config/scripts/init-prowlarr.py" ).AsConfig . ) | indent 2 }}

---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-jellyfin-script
data:
{{ ( tpl (.Files.Glob "config/scripts/init-jellyfin.py" ).AsConfig . ) | indent 2 }}
{{ if .Values.indexers }}
  indexers.json: {{ $.Values.indexers | toJson | quote}}
{{ end }}