apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-job
  labels:
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-3"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}-config-prepare"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: qbt-config-injector
          image: "busybox:latest"
          command:
          - "sh"
          - "-c"
          - |
            echo "-- DEBUG: qBitTorrent config file being used"
            cat /tmp/qBittorrent.conf
            if mkdir -p /mnt/qBittorrent/config/ ; then
              echo "-- INFO: Created qBitTorrent config directory"
            else
              echo "-- ERROR: An error occurred during the creation of the following path: /mnt/qBittorrent/config/"
              exit 1
            fi
            if cp -p /tmp/qBittorrent.conf /mnt/qBittorrent/config/qBittorrent.conf ; then
              echo "-- INFO: qBitTorrent config file moved in its config directory"
            else
              echo "-- ERROR: An error occurred during the qBitTorrent config copy to /mnt/qBittorrent/config/qBittorrent.conf"
              exit 1
            fi
            if chown -R 568:568 /mnt/ ; then
              echo "-- INFO: /mnt owner changed!"
            else
              echo "-- ERROR: An error occurred during the /mnt owner change"
              exit 1
            fi
            if chmod 0644 /mnt/qBittorrent/config/qBittorrent.conf ; then
              echo "-- INFO: qBitTorrent config file permissions changed!"
            else
              echo "-- ERROR: An error occurred while changing the qBitTorrent config file permissions"
              exit 1
            fi
            echo "-- DEBUG: /mnt/qBitTorrent/config/ directory content"
            ls -la /mnt/qBittorrent/config/
          volumeMounts:
            - name: torrent-config-volume
              mountPath: /mnt
            - name: profile-config
              mountPath: /tmp/qBittorrent.conf
              subPath: qBittorrent.conf
      volumes:
      - name: torrent-config-volume
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.torrentConfig.name }}
      - name: profile-config
        secret:
          secretName: qbittorrent-profile-config
          defaultMode: 0644
          # items:
          # - key: qBittorrent.conf
          #   path: qBittorrent.conf