apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-job
  labels:
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-3"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}-config-prepare"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: qbt-config-injector
          image: "busybox:latest"
          command:
          - "sh"
          - "-c"
          - |
            cat /tmp/qBittorrent.conf
            mkdir -p /mnt/qBittorrent/config/
            cp -p /tmp/qBittorrent.conf /mnt/qBittorrent/config/qBittorrent.conf
            chown -R 568:568 /mnt/
            chmod 0644 /mnt/qBittorrent/config/qBittorrent.conf
            ls -la /mnt/qBittorrent/config/
          volumeMounts:
            - name: torrent-config-volume
              mountPath: /mnt
            - name: profile-config
              mountPath: /tmp/qBittorrent.conf
              subPath: qBittorrent.conf
      volumes:
      - name: torrent-config-volume
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.torrentConfig.name }}
      - name: profile-config
        secret:
          secretName: qbittorrent-profile-config
          defaultMode: 0644
          # items:
          # - key: qBittorrent.conf
          #   path: qBittorrent.conf