# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-token-secret
# type: Opaque
# stringData:
#   api-token: {{ .Values.issuer.cloudFlareKey }}

---

apiVersion: v1
kind: Secret
metadata:
  name: servarr-api-key
type: Opaque
stringData:
  apikey: {{ .Values.global.apikey }}

---

apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-failed, before-hook-creation
  name: qbittorrent-profile-config
type: Opaque
data:
{{ ( tpl (.Files.Glob "config/qbittorrent/*.conf" ).AsSecrets . ) | indent 2 }}

---

apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-creds
type: Opaque
stringData:
  username: {{ .Values.torrent.username }}
  password: {{ .Values.torrent.password }}
