name: Helm Chart Build

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.1.0

      - name: Update dependencies
        run: helm dependency update

      - name: Helm Template
        run: helm template servarr . --debug -f .github/ci/ci-values.yaml
