name: Helm Chart Lint

on:
  push:
    branches:
      - 'dev'
      - 'ci/cache-usage' # test-purposes
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: v3.13.0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Fetch cached dependencies charts
        id: cache-charts
        uses: actions/cache/restore@v4
        with:
          path: servarr/charts
          key: dep-charts-${{ hashFiles('servarr/Chart.yaml') }}

      - name: Check servarr/ content
        run: ls -halF servarr

      - name: Check /charts content
        run: ls -halF servarr/charts

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs=servarr/ --charts=servarr/ --validate-maintainers=false --helm-dependency-extra-args ["--skip-refresh"]

      - name: Save dependencies charts in the cache
        if: ${{ steps.cache-charts.outputs.cache-hit != 'true' }}
        id: cache-charts-save
        uses: actions/cache/save@v4
        with:
          path: servarr/charts
          key: dep-charts-${{ hashFiles('servarr/Chart.yaml') }}