name: Helm Chart Doc Generator

on:
  push:
    branches:
      - 'dev'
      - 'docs/values-description'
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1

    - uses: EndBug/add-and-commit@v9.1.1
      with:
        message: "docs: regenerate chart README.md"
        add: "README.md"
        pull: "--rebase --autostash"