name: Helm Chart Doc Generator

on:
  push:
    branches:
      - 'dev'
      - 'docs/values-description'
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Render helm docs inside the README.md and push changes back to Working branch
      uses: shaybentk/helm-docs-action@v0.0.1
      with:
        working-dir: servarr
        git-push: "true"