name: Helm Chart Doc Generator

on:
  push:
    branches:
      - 'dev'
      - 'docs/values-description'
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout to current commit
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1
      with:
        git-push: true
        chart-search-root: ./servarr